# Generated by Django 5.1.2 on 2024-11-12 19:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 255 characters or fewer.",
                max_length=255,
                unique=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
